Repository interbit/interbit, pull requests merged in 2018-08, with the labels that each got.

#582 Don't run build:modules during heroku-postbuild - it runs in postinstall
  package.json
  packages/utils/src/standards/std.package.json
Labels: bug

#579 Add tests to blockExplorer reducer
  packages/interbit-ui-tools/src/tests/blockExplorer/reducer.test.js
  packages/interbit-ui-tools/src/tests/middleware/reducer.test.js
Labels: infrastructure

#580 Handle non blocking private chains
  packages/interbit-ui-tools/src/middleware/actions.js
  packages/interbit-ui-tools/src/middleware/constants.js
  packages/interbit-ui-tools/src/middleware/interbitGlobal.js
  packages/interbit-ui-tools/src/middleware/localDataStorage.js
  packages/interbit-ui-tools/src/middleware/middleware.js
  packages/interbit-ui-tools/src/middleware/reducer.js
  packages/interbit-ui-tools/src/middleware/sagas/chains.js
  packages/interbit-ui-tools/src/middleware/sagas/connections.js
  packages/interbit-ui-tools/src/middleware/sagas/index.js
  packages/interbit-ui-tools/src/middleware/sagas/interbit.js
  packages/interbit-ui-tools/src/middleware/sagas/privileges.js
  packages/interbit-ui-tools/src/middleware/selectors.js
  packages/interbit-ui-tools/src/tests/middleware/reducer.test.js
Labels: accounts, infrastructure

#586 Fix CAuth loop closes #585
  packages/app-account/src/components/ConnectFormAddMissingProfileField.js
  packages/app-account/src/containers/ChainConnect.js
Labels: accounts, bug

#589 Middleware test dependency injection
  packages/app-account/src/containers/Account.js
  packages/app-todo-list/src/containers/TodoList.js
  packages/interbit-ui-tools/src/middleware/browserContext/constants.js
  packages/interbit-ui-tools/src/middleware/browserContext/context.js
  packages/interbit-ui-tools/src/middleware/browserContext/dataStore.js
  packages/interbit-ui-tools/src/middleware/browserContext/index.js
  packages/interbit-ui-tools/src/middleware/browserContext/staticHtml.js
  packages/interbit-ui-tools/src/middleware/constants.js
  packages/interbit-ui-tools/src/middleware/middleware.js
  packages/interbit-ui-tools/src/middleware/sagas/chains.js
  packages/interbit-ui-tools/src/middleware/sagas/index.js
  packages/interbit-ui-tools/src/middleware/sagas/interbit.js
  packages/interbit-ui-tools/src/middleware/selectors.js
  packages/interbit-ui-tools/src/parameterEncoding/index.js
  packages/interbit-ui-tools/src/selectorScope.js
  packages/interbit-ui-tools/src/tests/blockExplorer/reducer.test.js
  packages/interbit-ui-tools/src/tests/blockExplorer/selectors.test.js
  packages/interbit-ui-tools/src/tests/exports.test.js
  packages/interbit-ui-tools/src/tests/middleware/reducer.test.js
  packages/interbit-ui-tools/src/tests/middleware/selectors.test.js
Labels: infrastructure

#595 Middleware unit tests and test context for integration tests
  packages/interbit-test/package.json
  packages/interbit-test/test/interbit.test.js
  packages/interbit-ui-tools/package.json
  packages/interbit-ui-tools/src/tests/browserContext/staticHtml.test.js
  packages/interbit-ui-tools/src/tests/middleware/middleware.test.js
  packages/interbit-ui-tools/src/tests/testContext/index.js
  packages/interbit-ui-tools/src/tests/testContext/testContext.test.js
  packages/interbit/package.json
Labels: infrastructure

#598 Generate a new manifest using unarmored keys.
  packages/app-account/public/index.html
  packages/interbit-template/public/index.html
  packages/platform-deploy/platform/interbit.manifest.json
Labels: bug

#619 Use distinct db_path for interbit tests
  packages/interbit-test/test/interbit.test.js
  packages/interbit-ui-tools/src/tests/testContext/testContext.test.js
  packages/interbit/src/chainManagement/startInterbit.js
  packages/interbit/src/file/packCovenants.js
  packages/interbit/src/scripts/build.js
  packages/interbit/src/scripts/deploy.js
  packages/interbit/src/scripts/start.js
  packages/interbit/src/tests/file/packCovenants.test.js
  packages/interbit/src/tests/integrationTests/build.js
  packages/interbit/src/tests/integrationTests/deploy.js
  packages/interbit/src/tests/integrationTests/start.js
Labels: infrastructure

#601 Add alias and chainIds to manifest entry for context
  packages/interbit/src/manifest/createManifestTree.js
  packages/interbit/src/tests/manifest/generateManifest.test.js
Labels: enhancement, sdk-cli

#643 Account profile page CSS grid scaffolding
  packages/app-account/src/constants/paths.js
  packages/app-account/src/containers/Profile.js
  packages/app-account/src/tests/rendering.test.js
  packages/interbit-ui-components/src/css/interbit.css
  packages/interbit-ui-components/src/css/interbit.css.map
  packages/interbit-ui-components/src/scss/interbit/_logo.scss
  packages/interbit-ui-components/src/scss/interbit/_scaffolding.scss
  packages/interbit-ui-components/src/scss/interbit/_variables.scss
Labels: accounts

#644 (app-account): remove unusued components and assets
  packages/app-account/src/components/ModalAppAccess.js
  packages/app-account/src/components/Navigation.js
  packages/app-account/src/img/profilePic.png
Labels: accounts, untidy! untidy!

#645 Standardize test environment to jest
  package-lock.json
  packages/interbit-covenant-tools/package.json
  packages/interbit-e2e/.babelrc
  packages/interbit-e2e/package.json
  packages/interbit-platform-tools/package.json
  packages/interbit-test/.babelrc
  packages/interbit-test/package.json
  packages/interbit-test/test/interbit.test.js
  packages/utils/package.json
  packages/web-auth-endpoint/.babelrc
  packages/web-auth-endpoint/package.json
Labels: untidy! untidy!

#631 Covenant aliases correctly mapped to hashes in the manifest
  packages/interbit/src/manifest/createManifestTree.js
  packages/interbit/src/tests/manifest/generateManifest.test.js
  packages/interbit/src/tests/testData/index.js
Labels: bug

#648 Remove blocks from interbit-covenant-tools
  packages/interbit-covenant-tools/src/coreCovenant/constants.js
  packages/interbit-covenant-tools/src/coreCovenant/selectors.js
  packages/interbit-covenant-tools/src/tests/exports.test.js
Labels: untidy! untidy!

#649 Reset my data retread
  packages/app-account/src/components/DeleteData.js
  packages/app-account/src/containers/Account.js
  packages/app-account/src/content/account.js
  packages/app-account/src/interbit/my-account/actions.js
  packages/app-account/src/interbit/my-account/index.js
  packages/app-account/src/tests/covenants/my-account.covenant.test.js
  packages/interbit-ui-tools/src/middleware/selectors.js
Labels: accounts

#654 Parameter encoding tests
  packages/interbit-ui-tools/src/parameterEncoding/index.js
  packages/interbit-ui-tools/src/tests/parameterEncoding/parameterEncoding.test.js
Labels: sdk-ui-tools, untidy! untidy!

#653 (interbit-ui-components): update webpack config
  packages/interbit-ui-components/webpack.config.js
Labels: sdk-ui-components

#655 Update loaded chains and apply initial covenants on deploy
  package-lock.json
  packages/interbit-covenant-tools/src/manifest/manifestSelectors.js
  packages/interbit/src/chainManagement/destroyRemovedChains.js
  packages/interbit/src/chainManagement/index.js
  packages/interbit/src/chainManagement/initializeCovenants.js
  packages/interbit/src/scripts/deploy.js
Labels: sdk-cli

#661 Update broken heroku urls for stg/prod
  packages/interbit-platform-tools/src/index.js
Labels: accounts, bug, infrastructure

#664 Add new pill button component
  packages/app-account/src/css/App.css
  packages/app-account/src/scss/App.scss
  packages/interbit-ui-components/src/assets/icons/reset.svg
  packages/interbit-ui-components/src/assets/icons/trash.svg
  packages/interbit-ui-components/src/components/UIKit/IconButton.js
  packages/interbit-ui-components/src/css/interbit.css
  packages/interbit-ui-components/src/css/interbit.css.map
  packages/interbit-ui-components/src/scss/interbit/_content-bar.scss
  packages/interbit-ui-components/src/scss/interbit/_icon-button.scss
  packages/interbit-ui-components/src/tests/uiKit.test.js
Labels: accounts

#662 Clean-up interbit DBs after tests
  packages/interbit-test/package.json
  packages/interbit-test/test/interbit.test.js
  packages/interbit-ui-tools/package.json
  packages/interbit-ui-tools/src/tests/testContext/testContext.test.js
  packages/interbit/src/tests/file/packCovenants.test.js
  packages/interbit/src/tests/integrationTests/build.js
  packages/interbit/src/tests/integrationTests/deploy.js
  packages/interbit/src/tests/integrationTests/start.js
Labels: untidy! untidy!

#659 interbit-ui-tools loadChainSaga/unloadChainSaga
  packages/interbit-ui-tools/src/middleware/actions.js
  packages/interbit-ui-tools/src/middleware/constants.js
  packages/interbit-ui-tools/src/middleware/middleware.js
  packages/interbit-ui-tools/src/middleware/reducer.js
  packages/interbit-ui-tools/src/middleware/sagas/chains.js
  packages/interbit-ui-tools/src/middleware/sagas/index.js
  packages/interbit-ui-tools/src/middleware/selectors.js
  packages/interbit-ui-tools/src/tests/exports.test.js
  packages/interbit-ui-tools/src/tests/middleware/middleware.test.js
  packages/interbit-ui-tools/src/tests/middleware/reducer.test.js
  packages/interbit-ui-tools/src/tests/middleware/sagas.test.js
Labels: sdk-ui-tools

#673 Replace assert's deepEqual with deepStrictEqual
  packages/app-account/src/tests/covenants/control.covenant.test.js
  packages/app-account/src/tests/covenants/github-kyc.covenant.test.js
  packages/app-project/src/tests/chain/my-projects.test.js
  packages/app-project/src/tests/chain/project.test.js
  packages/app-sdk-incrementer/src/tests/chain/incrementCovenant.test.js
  packages/app-todo-list/src/tests/interbit/controlCovenant.test.js
  packages/app-todo-list/src/tests/interbit/privateCovenant.test.js
  packages/app-uth-ex/src/tests/chain/hubCovenant.test.js
  packages/app-uth-ex/src/tests/chain/spokeCovenant.test.js
  packages/interbit-covenant-tools/src/tests/config/configSelectors.test.js
  packages/interbit-covenant-tools/src/tests/coreCovenant/revokeReadJoin.test.js
  packages/interbit-covenant-tools/src/tests/coreCovenant/revokeWriteJoin.test.js
  packages/interbit-covenant-tools/src/tests/manifest/manifestSelectors.test.js
  packages/interbit-covenant-tools/src/tests/mergeCovenants/mergeCovenants.test.js
  packages/interbit-template/src/tests/interbit/controlCovenant.test.js
  packages/interbit-template/src/tests/interbit/privateCovenant.test.js
  packages/interbit-test/test/genesisBlocks.test.js
  packages/interbit-test/test/interbit.test.js
  packages/interbit/src/tests/args/args.test.js
  packages/interbit/src/tests/args/getArg.test.js
  packages/interbit/src/tests/chainManagement/configureJoins.test.js
  packages/interbit/src/tests/chainManagement/generateDeploymentDetails.test.js
  packages/interbit/src/tests/file/updateIndexHtml.test.js
  packages/interbit/src/tests/integrationTests/assertChainsConfigured.js
  packages/interbit/src/tests/integrationTests/build.js
  packages/interbit/src/tests/scripts/hoist.test.js
  packages/utils/src/tests/build.test.js
Labels: bug, untidy! untidy!
