Repository interbit/interbit, pull requests merged in 2018-05, with the labels that each got.

#123 Allow heroku to pick port for web-auth-endpoint
  packages/web-auth-endpoint/package.json
  packages/web-auth-endpoint/src/index.js
Labels: accounts, infrastructure

#142 Web auth endpoint up on heroku, communicating with blockmaster node
  packages/app-account/interbit.config.js
  packages/app-account/interbit.prod.config.js
  packages/app-account/public/index.html
  packages/interbit-cli/scripts/deploy.js
  packages/interbit/src/chainManagement/configureChains.js
  packages/interbit/src/chainManagement/configureJoins.js
  packages/interbit/src/chainManagement/createChains.js
  packages/interbit/src/chainManagement/joinChains.js
  packages/interbit/src/index.js
  packages/interbit/src/scripts/deploy.js
  packages/interbit/src/scripts/hoist.js
  packages/interbit/tests/chainManagement/configureJoins.test.js
  packages/interbit/tests/hoist.test.js
  packages/platform-deploy/platform/interbit.manifest.json
  packages/template/public/index.html
  packages/web-auth-endpoint/keyPair.js
  packages/web-auth-endpoint/package.json
  packages/web-auth-endpoint/src/authServer.js
  packages/web-auth-endpoint/src/index.js
  packages/web-auth-endpoint/src/interbitNode.js
  packages/web-auth-endpoint/src/networkConfig.js
  packages/web-auth-endpoint/src/node.js
  packages/web-auth-endpoint/src/proxy.js
Labels: accounts, infrastructure

#146 Update interbit-middleware documentation
  docs/gitbook/reference/interbit-middleware/README.md
  docs/gitbook/reference/interbit-middleware/selectors.md
Labels: sdk-docs

#145 Release 0.4.17
  CHANGELOG.md
  docs/CHANGELOG.md
  docs/package.json
  lerna.json
  packages/app-account/CHANGELOG.md
  packages/app-account/package.json
  packages/app-account/src/interbit/control/package.json
  packages/app-account/src/interbit/github-kyc/package.json
  packages/app-account/src/interbit/my-account/package.json
  packages/app-app-store/CHANGELOG.md
  packages/app-app-store/package.json
  packages/app-interbit-io/CHANGELOG.md
  packages/app-interbit-io/package.json
  packages/app-project/CHANGELOG.md
  packages/app-project/package.json
  packages/app-project/src/interbit/my-projects/package.json
  packages/app-project/src/interbit/project/package.json
  packages/app-sdk-incrementer/CHANGELOG.md
  packages/app-sdk-incrementer/package.json
  packages/app-uth-ex/CHANGELOG.md
  packages/app-uth-ex/package.json
  packages/app-uth-ex/src/interbit/hub/package.json
  packages/app-uth-ex/src/interbit/spoke/package.json
  packages/interbit-cli/CHANGELOG.md
  packages/interbit-cli/package.json
  packages/interbit-covenant-tools/CHANGELOG.md
  packages/interbit-covenant-tools/package.json
  packages/interbit-platform-tools/CHANGELOG.md
  packages/interbit-platform-tools/package.json
  packages/interbit-test/CHANGELOG.md
  packages/interbit-test/package.json
  packages/interbit-ui-components/CHANGELOG.md
  packages/interbit-ui-components/package.json
  packages/interbit-ui-tools/CHANGELOG.md
  packages/interbit-ui-tools/package.json
  packages/interbit/CHANGELOG.md
  packages/interbit/package.json
  packages/platform-deploy/CHANGELOG.md
  packages/platform-deploy/package.json
  packages/template/CHANGELOG.md
  packages/template/package.json
  packages/template/src/interbit/control/package.json
  packages/template/src/interbit/private/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  packages/utils/src/standards/req.app-package.json
  packages/utils/src/standards/std.lerna.json
  packages/web-auth-endpoint/CHANGELOG.md
  packages/web-auth-endpoint/package.json
Labels: sdk-cli

#153 Ensures es5 under the `interbit` folder
  packages/template/src/interbit/.eslintrc
  packages/template/src/interbit/private/actionTypes.js
Labels: bug
