Repository interbit/interbit, pull requests merged in 2018-07, with the labels that each got.

#508 Improved Chain Joins coverage
  docs/dictionaries/interbit.dic
  docs/gitbook/Contents.md
  docs/gitbook/GLOSSARY.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/architecture/chain_joins.adoc
  docs/gitbook/architecture/code/create_chain-dispatch.js
  docs/gitbook/architecture/permission_model.adoc
  docs/gitbook/examples/README.md
  docs/gitbook/examples/initialize.md
  docs/gitbook/examples/joining.md
  docs/gitbook/examples/order-books.md
  docs/gitbook/examples/template.md
  docs/gitbook/examples/to-do-list.md
  docs/gitbook/key-concepts/README.adoc
  docs/gitbook/key-concepts/README.md
  docs/gitbook/key-concepts/actions.adoc
  docs/gitbook/key-concepts/chain_joins.adoc
  docs/gitbook/key-concepts/configuration.adoc
  docs/gitbook/key-concepts/covenants.adoc
  docs/gitbook/key-concepts/hypervisor.adoc
  docs/gitbook/key-concepts/sagas.adoc
  docs/gitbook/key-concepts/smart_contracts.adoc
  docs/gitbook/key-concepts/state.adoc
  docs/gitbook/reference/interbit-cli/config.md
  docs/gitbook/reference/interbit-core/chainInterface/getState.md
  docs/gitbook/reference/interbit-core/cli/getState.md
  docs/gitbook/reference/interbit-core/hypervisor/getState.md
  docs/gitbook/reference/interbit/startInterbit.md
Labels: sdk-docs

#530 Re-worked "Chain Architecture" topic into "Chain Topology":
  docs/artwork/control_by_proxy.ai
  docs/artwork/hierarchical_throughput.ai
  docs/artwork/hub_and_connected_spoke.ai
  docs/artwork/hub_and_spoke.ai
  docs/artwork/spoke_control.ai
  docs/gitbook/SUMMARY.md
  docs/gitbook/architecture/chain-architecture.md
  docs/gitbook/architecture/topology/README.adoc
  docs/gitbook/architecture/topology/considerations.adoc
  docs/gitbook/architecture/topology/img/control_by_proxy.svg
  docs/gitbook/architecture/topology/img/hierarchical_throughput.svg
  docs/gitbook/architecture/topology/img/hub_and_connected_spoke.svg
  docs/gitbook/architecture/topology/img/hub_and_spoke.svg
  docs/gitbook/architecture/topology/img/spoke_control.svg
  docs/gitbook/architecture/topology/patterns.adoc
  docs/theme-interbit/_assets/website/interbit.css
Labels: sdk-docs

#532 Doc Design Work
  docs/theme-interbit/_assets/website/images/icon-caution.svg
  docs/theme-interbit/_assets/website/images/icon-important.svg
  docs/theme-interbit/_assets/website/images/icon-note.svg
  docs/theme-interbit/_assets/website/images/icon-tip.svg
  docs/theme-interbit/_assets/website/interbit.css
  docs/theme-interbit/index.js
Labels: sdk-docs

#533 Deploy root chain 371
  packages/app-todo-list/src/tests/exports.test.js
  packages/interbit-covenant-tools/package.json
  packages/interbit-covenant-tools/src/index.js
  packages/interbit-covenant-tools/src/rootCovenant/index.js
  packages/interbit-covenant-tools/src/rootCovenant/package.json
  packages/interbit-covenant-tools/src/tests/exports.test.js
  packages/interbit-covenant-tools/src/tests/rootCovenant/rootCovenant.test.js
  packages/interbit-template/src/tests/exports.test.js
  packages/interbit/src/chainManagement/configureChains.js
  packages/interbit/src/chainManagement/setRootChainManifest.js
  packages/interbit/src/file/index.js
  packages/interbit/src/file/packCovenants.js
  packages/interbit/src/manifest/index.js
  packages/interbit/src/scripts/build.js
  packages/interbit/src/scripts/deploy.js
Labels: sdk-cli, usability

#537 Fix build watch in interbit-covenant-tools. Closes #234
  packages/interbit-ui-components/webpack.config.js
Labels: bug

#538 Update interbit-core to 0.14.0
  packages/app-account/public/index.html
  packages/app-app-store/public/index.html
  packages/app-project/public/index.html
  packages/app-sdk-incrementer/public/index.html
  packages/app-todo-list/public/index.html
  packages/app-uth-ex/public/index.html
  packages/interbit-cli/package.json
  packages/interbit-covenant-tools/package.json
  packages/interbit-template/public/index.html
  packages/interbit-test/package.json
  packages/interbit-test/test/genesisBlocks.test.js
  packages/interbit-test/test/interbit.test.js
  packages/interbit-ui-tools/package.json
  packages/interbit-ui-tools/src/actions.js
  packages/interbit-ui-tools/src/interbitGlobal.js
  packages/interbit-ui-tools/src/localDataStorage/index.js
  packages/interbit-ui-tools/src/middleware.js
  packages/interbit-ui-tools/src/reducer.js
  packages/interbit-ui-tools/src/sagas/chains.js
  packages/interbit-ui-tools/src/sagas/index.js
  packages/interbit/package.json
Labels: infrastructure, sdk-ui-tools

#542 Publish 0.4.42
  CHANGELOG.md
  docs/CHANGELOG.md
  docs/package.json
  lerna.json
  packages/app-account/CHANGELOG.md
  packages/app-account/package.json
  packages/app-account/src/interbit/control/package.json
  packages/app-account/src/interbit/github-kyc/package.json
  packages/app-account/src/interbit/my-account/package.json
  packages/app-app-store/CHANGELOG.md
  packages/app-app-store/package.json
  packages/app-interbit-io/CHANGELOG.md
  packages/app-interbit-io/package.json
  packages/app-project/CHANGELOG.md
  packages/app-project/package.json
  packages/app-project/src/interbit/my-projects/package.json
  packages/app-project/src/interbit/project/package.json
  packages/app-sdk-incrementer/CHANGELOG.md
  packages/app-sdk-incrementer/package.json
  packages/app-todo-list/CHANGELOG.md
  packages/app-todo-list/package.json
  packages/app-todo-list/src/interbit/control/package.json
  packages/app-todo-list/src/interbit/private/package.json
  packages/app-uth-ex/CHANGELOG.md
  packages/app-uth-ex/package.json
  packages/app-uth-ex/src/interbit/hub/package.json
  packages/app-uth-ex/src/interbit/spoke/package.json
  packages/interbit-cli/CHANGELOG.md
  packages/interbit-cli/package.json
  packages/interbit-covenant-tools/CHANGELOG.md
  packages/interbit-covenant-tools/package.json
  packages/interbit-e2e/CHANGELOG.md
  packages/interbit-e2e/package.json
  packages/interbit-platform-tools/CHANGELOG.md
  packages/interbit-platform-tools/package.json
  packages/interbit-template/CHANGELOG.md
  packages/interbit-template/package.json
  packages/interbit-template/src/interbit/control/package.json
  packages/interbit-template/src/interbit/private/package.json
  packages/interbit-test/CHANGELOG.md
  packages/interbit-test/package.json
  packages/interbit-ui-components/CHANGELOG.md
  packages/interbit-ui-components/package.json
  packages/interbit-ui-tools/CHANGELOG.md
  packages/interbit-ui-tools/package.json
  packages/interbit/CHANGELOG.md
  packages/interbit/package.json
  packages/platform-deploy/CHANGELOG.md
  packages/platform-deploy/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  packages/utils/src/standards/req.app-package.json
  packages/utils/src/standards/std.lerna.json
  packages/web-auth-endpoint/CHANGELOG.md
  packages/web-auth-endpoint/package.json
Labels: infrastructure

#541 Improve interbit package test coverage
  packages/interbit/src/file/packCovenants.js
  packages/interbit/src/scripts/keys.js
  packages/interbit/src/tests/args/args.test.js
  packages/interbit/src/tests/args/getArg.test.js
  packages/interbit/src/tests/chainManagement/generateDeploymentDetails.test.js
  packages/interbit/src/tests/file/packCovenants.test.js
  packages/interbit/src/tests/file/updateIndexHtml.test.js
  packages/interbit/src/tests/scripts/build.test.js
  packages/interbit/src/tests/scripts/hoist.test.js
  packages/interbit/src/tests/scripts/keys.test.js
  packages/interbit/src/tests/testData/covenant/index.js
  packages/interbit/src/tests/testData/covenant/package.json
  packages/interbit/src/tests/testData/index.js
  packages/interbit/src/tests/testData/interbit.config.js
  packages/interbit/src/tests/testData/interbit.manifest.json
  packages/interbit/src/tests/testData/keyPair.json
Labels: enhancement

#547 Test coverage
  package-lock.json
  packages/app-account/src/containers/CreateAccount.js
  packages/app-account/src/containers/PageContainer.js
  packages/app-account/src/tests/rendering.test.js
  packages/app-app-store/src/containers/AppDetails.js
  packages/app-app-store/src/tests/Rendering.test.js
  packages/app-interbit-io/src/tests/Rendering.test.js
  packages/app-project/src/tests/rendering.test.js
  packages/interbit-template/src/tests/App.test.js
  packages/interbit-template/src/tests/rendering.test.js
Labels: infrastructure

#571 Add watch as a dependency of interbit
  packages/interbit/package.json
Labels: bug

#574 Remove unneeded sponsor chain after 2nd device login
  packages/interbit-ui-tools/src/middleware/actions.js
  packages/interbit-ui-tools/src/middleware/constants.js
  packages/interbit-ui-tools/src/middleware/interbitGlobal.js
  packages/interbit-ui-tools/src/middleware/localDataStorage.js
  packages/interbit-ui-tools/src/middleware/reducer.js
  packages/interbit-ui-tools/src/middleware/sagas/chains.js
  packages/interbit-ui-tools/src/tests/middleware/reducer.test.js
Labels: accounts, infrastructure

#578 Revert "Preserve browser hypervisor chain id"
  packages/interbit-ui-tools/src/middleware/interbitGlobal.js
  packages/interbit-ui-tools/src/middleware/localDataStorage.js
Labels: bug, infrastructure
